// 契约表分组：果园、批次、采收与溯源。
// 对应 Django 的 Orchard / FruitTreeArchive / SalesBatch / HarvestArchive /
// BatchQualitySample / TraceEvent 共 6 个模型。
// 拆成两个切片的原因：`batch_quality_sample.product_id` 外键指向 citrus_product，
// 因此它必须晚于 commerce_tables::PRODUCT_DDL 执行（见 bootstrap.rs 的执行顺序注释）。
// 注意：`trace_event` 的 previous_hash/evidence_hash 由 API 层按哈希链规则写入，
// DDL 只负责列与约束，不涉及 sha256 逻辑。

pub(super) const DDL: &[&str] = &[
    // Orchard -> orchard
    r#"CREATE TABLE IF NOT EXISTS orchard (
            id UUID PRIMARY KEY,
            code VARCHAR(32) NOT NULL UNIQUE,
            owner_id UUID NULL REFERENCES "user"(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
            name VARCHAR(120) NOT NULL,
            grower_name VARCHAR(80) NOT NULL DEFAULT '',
            province VARCHAR(60) NOT NULL DEFAULT '江西省',
            city VARCHAR(60) NOT NULL DEFAULT '赣州市',
            county VARCHAR(60) NOT NULL,
            detail_address VARCHAR(255) NOT NULL DEFAULT '',
            latitude DOUBLE PRECISION NULL,
            longitude DOUBLE PRECISION NULL,
            area_mu NUMERIC(10, 2) NULL,
            main_variety VARCHAR(80) NOT NULL DEFAULT '纽荷尔脐橙',
            tagline VARCHAR(160) NOT NULL DEFAULT '',
            feature_tags JSONB NOT NULL DEFAULT '[]'::jsonb,
            story TEXT NOT NULL DEFAULT '',
            cover_image_url VARCHAR(500) NOT NULL DEFAULT '',
            gallery_urls JSONB NOT NULL DEFAULT '[]'::jsonb,
            video_urls JSONB NOT NULL DEFAULT '[]'::jsonb,
            certifications JSONB NOT NULL DEFAULT '[]'::jsonb,
            status VARCHAR(20) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'verified', 'inactive')),
            verification_note VARCHAR(255) NOT NULL DEFAULT '',
            verified_at TIMESTAMPTZ NULL,
            created_at TIMESTAMPTZ NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL
        )"#,
    r#"CREATE INDEX IF NOT EXISTS idx_orchard_owner_id ON orchard(owner_id)"#,
    // FruitTreeArchive -> fruit_tree_archive
    r#"CREATE TABLE IF NOT EXISTS fruit_tree_archive (
            id UUID PRIMARY KEY,
            trace_code VARCHAR(40) NOT NULL UNIQUE,
            orchard_id UUID NOT NULL REFERENCES orchard(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
            tree_number VARCHAR(40) NOT NULL,
            plot_name VARCHAR(80) NOT NULL DEFAULT '',
            variety VARCHAR(80) NOT NULL,
            planted_year INTEGER NULL CHECK (planted_year >= 0),
            growth_stage VARCHAR(80) NOT NULL DEFAULT '',
            health_status VARCHAR(24) NOT NULL DEFAULT 'healthy' CHECK (health_status IN ('healthy', 'watch', 'maintenance')),
            growth_summary TEXT NOT NULL DEFAULT '',
            latest_temperature NUMERIC(5, 1) NULL,
            latest_humidity NUMERIC(5, 1) NULL,
            last_observed_at TIMESTAMPTZ NULL,
            cover_image_url VARCHAR(500) NOT NULL DEFAULT '',
            image_urls JSONB NOT NULL DEFAULT '[]'::jsonb,
            video_urls JSONB NOT NULL DEFAULT '[]'::jsonb,
            is_featured BOOLEAN NOT NULL DEFAULT FALSE,
            created_at TIMESTAMPTZ NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL,
            CONSTRAINT unique_tree_number_per_orchard UNIQUE (orchard_id, tree_number)
        )"#,
    r#"CREATE INDEX IF NOT EXISTS idx_fruit_tree_archive_orchard_id ON fruit_tree_archive(orchard_id)"#,
    // SalesBatch -> sales_batch（code/trace_code 由应用层生成，trace_code 的默认值是 Python 函数，SQL 不设默认）
    r#"CREATE TABLE IF NOT EXISTS sales_batch (
            id UUID PRIMARY KEY,
            code VARCHAR(40) NOT NULL UNIQUE,
            trace_code VARCHAR(40) NOT NULL UNIQUE,
            orchard_id UUID NOT NULL REFERENCES orchard(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
            title VARCHAR(160) NOT NULL,
            subtitle VARCHAR(255) NOT NULL DEFAULT '',
            status VARCHAR(24) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'warming', 'open', 'closed', 'harvesting', 'fulfilling', 'completed', 'cancelled')),
            planned_quantity INTEGER NOT NULL DEFAULT 0 CHECK (planned_quantity >= 0),
            sold_quantity INTEGER NOT NULL DEFAULT 0 CHECK (sold_quantity >= 0),
            open_at TIMESTAMPTZ NULL,
            close_at TIMESTAMPTZ NULL,
            expected_harvest_start DATE NULL,
            expected_harvest_end DATE NULL,
            expected_ship_start DATE NULL,
            expected_ship_end DATE NULL,
            maturity_standard VARCHAR(255) NOT NULL DEFAULT '',
            quality_commitment TEXT NOT NULL DEFAULT '',
            natural_variation_note TEXT NOT NULL DEFAULT '',
            aftersale_policy TEXT NOT NULL DEFAULT '',
            cover_image_url VARCHAR(500) NOT NULL DEFAULT '',
            live_image_urls JSONB NOT NULL DEFAULT '[]'::jsonb,
            environment_summary JSONB NOT NULL DEFAULT '{}'::jsonb,
            payment_mode VARCHAR(24) NOT NULL DEFAULT 'full' CHECK (payment_mode IN ('full', 'deposit_balance')),
            deposit_ratio NUMERIC(5, 2) NOT NULL DEFAULT 0,
            procurement_cost_per_box NUMERIC(10, 2) NOT NULL DEFAULT 0,
            sorting_cost_per_box NUMERIC(10, 2) NOT NULL DEFAULT 0,
            packaging_cost_per_box NUMERIC(10, 2) NOT NULL DEFAULT 0,
            shipping_cost_per_box NUMERIC(10, 2) NOT NULL DEFAULT 0,
            aftersale_reserve_per_box NUMERIC(10, 2) NOT NULL DEFAULT 0,
            promotion_cost_per_box NUMERIC(10, 2) NOT NULL DEFAULT 0,
            payment_fee_rate NUMERIC(5, 2) NOT NULL DEFAULT 0,
            is_featured BOOLEAN NOT NULL DEFAULT FALSE,
            created_at TIMESTAMPTZ NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL
        )"#,
    r#"CREATE INDEX IF NOT EXISTS idx_sales_batch_orchard_id ON sales_batch(orchard_id)"#,
    // HarvestArchive -> harvest_archive
    r#"CREATE TABLE IF NOT EXISTS harvest_archive (
            id UUID PRIMARY KEY,
            harvest_code VARCHAR(40) NOT NULL UNIQUE,
            batch_id UUID NOT NULL REFERENCES sales_batch(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
            tree_id UUID NULL REFERENCES fruit_tree_archive(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
            harvested_at TIMESTAMPTZ NOT NULL,
            picker VARCHAR(80) NOT NULL,
            plot_name VARCHAR(80) NOT NULL DEFAULT '',
            harvest_method VARCHAR(120) NOT NULL DEFAULT '人工分批采摘',
            quantity_kg NUMERIC(10, 2) NOT NULL,
            maturity_brix NUMERIC(4, 1) NULL,
            grade VARCHAR(60) NOT NULL DEFAULT '',
            pre_harvest_status VARCHAR(255) NOT NULL DEFAULT '',
            harvest_weather VARCHAR(80) NOT NULL DEFAULT '',
            fruit_condition VARCHAR(24) NOT NULL DEFAULT 'good' CHECK (fruit_condition IN ('good', 'watch', 'rejected')),
            appearance_note VARCHAR(255) NOT NULL DEFAULT '',
            pest_status VARCHAR(160) NOT NULL DEFAULT '',
            damage_rate_percent NUMERIC(5, 2) NULL,
            summary TEXT NOT NULL DEFAULT '',
            image_urls JSONB NOT NULL DEFAULT '[]'::jsonb,
            video_urls JSONB NOT NULL DEFAULT '[]'::jsonb,
            created_at TIMESTAMPTZ NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL
        )"#,
    r#"CREATE INDEX IF NOT EXISTS idx_harvest_archive_batch_id ON harvest_archive(batch_id)"#,
    r#"CREATE INDEX IF NOT EXISTS idx_harvest_archive_tree_id ON harvest_archive(tree_id)"#,
    // TraceEvent -> trace_event（哈希链字段由 API 层写入，默认空串）
    r#"CREATE TABLE IF NOT EXISTS trace_event (
            id UUID PRIMARY KEY,
            batch_id UUID NOT NULL REFERENCES sales_batch(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
            event_type VARCHAR(24) NOT NULL CHECK (event_type IN ('orchard', 'environment', 'quality', 'harvest', 'sorting', 'packing', 'shipping', 'aftersale')),
            source_type VARCHAR(24) NOT NULL DEFAULT 'operator' CHECK (source_type IN ('operator', 'farmer', 'sensor', 'quality', 'logistics')),
            occurred_at TIMESTAMPTZ NOT NULL,
            title VARCHAR(120) NOT NULL,
            description TEXT NOT NULL DEFAULT '',
            location VARCHAR(160) NOT NULL DEFAULT '',
            actor VARCHAR(80) NOT NULL DEFAULT '',
            source_reference VARCHAR(160) NOT NULL DEFAULT '',
            image_urls JSONB NOT NULL DEFAULT '[]'::jsonb,
            data JSONB NOT NULL DEFAULT '{}'::jsonb,
            previous_hash VARCHAR(64) NOT NULL DEFAULT '',
            evidence_hash VARCHAR(64) NOT NULL DEFAULT '',
            recorded_at TIMESTAMPTZ NOT NULL
        )"#,
    r#"CREATE INDEX IF NOT EXISTS idx_trace_event_batch_id ON trace_event(batch_id)"#,
];

// BatchQualitySample -> batch_quality_sample
// 依赖 citrus_product（commerce_tables::PRODUCT_DDL），必须在商品表之后执行。
pub(super) const QUALITY_DDL: &[&str] = &[
    r#"CREATE TABLE IF NOT EXISTS batch_quality_sample (
            id UUID PRIMARY KEY,
            batch_id UUID NOT NULL REFERENCES sales_batch(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
            product_id UUID NULL REFERENCES citrus_product(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
            harvest_archive_id UUID NULL REFERENCES harvest_archive(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
            sampled_at TIMESTAMPTZ NOT NULL,
            inspection_stage VARCHAR(24) NOT NULL DEFAULT 'pre_harvest' CHECK (inspection_stage IN ('growing', 'pre_harvest', 'at_harvest', 'post_sorting')),
            health_status VARCHAR(24) NOT NULL DEFAULT 'qualified' CHECK (health_status IN ('qualified', 'watch', 'rejected')),
            sample_size INTEGER NOT NULL DEFAULT 1 CHECK (sample_size >= 0),
            sweetness_brix NUMERIC(4, 1) NULL,
            acidity NUMERIC(5, 2) NULL,
            average_weight_grams INTEGER NULL CHECK (average_weight_grams >= 0),
            diameter_mm NUMERIC(5, 1) NULL,
            grade VARCHAR(60) NOT NULL DEFAULT '',
            result VARCHAR(120) NOT NULL DEFAULT '符合本批次标准',
            appearance_status VARCHAR(160) NOT NULL DEFAULT '',
            pest_status VARCHAR(160) NOT NULL DEFAULT '',
            pesticide_residue_result VARCHAR(160) NOT NULL DEFAULT '',
            inspector VARCHAR(80) NOT NULL DEFAULT '',
            report_image_url VARCHAR(500) NOT NULL DEFAULT '',
            note TEXT NOT NULL DEFAULT '',
            created_at TIMESTAMPTZ NOT NULL
        )"#,
    r#"CREATE INDEX IF NOT EXISTS idx_batch_quality_sample_batch_id ON batch_quality_sample(batch_id)"#,
    r#"CREATE INDEX IF NOT EXISTS idx_batch_quality_sample_product_id ON batch_quality_sample(product_id)"#,
    r#"CREATE INDEX IF NOT EXISTS idx_batch_quality_sample_harvest_archive_id ON batch_quality_sample(harvest_archive_id)"#,
];
